shell /usr/bin/zsh

include current-theme.conf

# FONTS
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

# TRANSPARENCY
background_opacity 0.95

# LAYOUT
enabled_layouts tall,*

# WINDOWS
window_border_width 2pt

# TABS
tab_bar_style powerline
active_tab_background  #444444
active_tab_foreground  #5fd700
tab_bar_margin_height 0.0 2.0
tab_bar_margin_color  #4f4f4f
tab_activity_symbol *

# SHORTCUTS
# Unbind ctl+shift+left and ctl+shift+right
map ctrl+shift+left forward
map ctrl+shift+right forward
map shift+left forward
map shift+right forward

# Rebind ctrl+alt+shift+left and ctrl+alt+shift+right to previous and next tab
map ctrl+shift+[ previous_tab
map ctrl+shift+] next_tab
map ctrl+alt+shift+left previous_window
map ctrl+alt+shift+right next_window
