shell /usr/bin/zsh

include current-theme.conf

# FONTS
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

# TRANSPARENCY
background_opacity 0.9

# SHORTCUTS
# Unbind ctl+shift+left and ctl+shift+right
map ctrl+shift+left forward
map ctrl+shift+right forward
map shift+left forward
map shift+right forward
